version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop-rspec
    versions:
    - 1.41.0
  commit-message:
    prefix: bump
    include: scope
